services:
  - type: web
    name: job-board-server
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run migrate:deploy && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 4000
